include $(HOME)/Makefile_templates/Makefile

midtread.svg:	midtread.ipynb
		jupyter nbconvert --to notebook --inplace --execute midtread.ipynb

TMPs += midtread.svg

midrise.svg:	midrise.ipynb
		jupyter nbconvert --to notebook --inplace --execute midrise.ipynb

TMPs += midrise.svg

deadzone.svg:	deadzone.ipynb
		jupyter nbconvert --to notebook --inplace --execute deadzone.ipynb

TMPs += deadzone.svg
