include $(HOME)/Makefile_templates/Makefile

midtread.svg:	midtread.ipynb
		jupyter nbconvert --to notebook --inplace --execute midtread.ipynb

TMPs += midtread.svg midtread.pdf

midrise.svg:	midrise.ipynb
		jupyter nbconvert --to notebook --inplace --execute midrise.ipynb

TMPs += midrise.svg midrise.pdf

deadzone.svg:	deadzone.ipynb
		jupyter nbconvert --to notebook --inplace --execute deadzone.ipynb

TMPs += deadzone.svg deadzone.pdf
